---
title: "Post I: Temporal Niche Partitioning"
author: "Adam Bakewell"
date: "07/08/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
***

We're driving our fellow mammals into the night... descriptions of human disturbance, scale of effects, key results from the paper...

Take the greater kudu...

Second highest is the nine-banded armadillo...

Rounding up the top three, the black bear...

Go through the stats and here talk about the risk factors that are associated with being disturbed. Link it in with the examples that you've just given. If things like herb/carn are about the same level of risk then just be listing species and talk about how astonishing it is that we're affecting things on this level...

But then... temporal niche partitioning...

Species that had low effect sizes (elk and striped skunk) go into the original papers, cross reference what they say with this one... try and tease out why these species appear to be unaffected, what's the adaptation.

What's the future, a sassier animal kingdom?

*Author's note:*  
This was one of my candidate stories for [Episode X](http://genericdrift.com/gd-x-pangaea-park) of *Generic Drift*, but Harvey edited it out - I think because he didn't believe me that lions and hyaenas had huge niche overlap! Me, fake news? Never! -- Adam